title: Something Wicked has come this way already
author: bill-richards
email: github@greyskin.co.uk
description: > # this means to ignore newlines until "baseurl:"
  All was quiet in the office that evening, all except for the gentle tap, tap, tapping of the computer keyboard
  ... work was being done.
# social links
twitter_username: not_a_whisper # DO NOT include the @ character, or else the build will fail!
github_username:  bill-richards # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
