title: Something Wicked this way came
author: Bill Richards
email: github@greyskin.co.uk

description: > 
  All was quiet in the office that evening, all except for the gentle tap, tap, tapping of the computer keyboard
  ... work was being done.

# social links
twitter_username: not_a_whisper 
github_username:  bill-richards 

show_excerpts: false 
theme: minima
